export const CHANGE_START_BUTTON_STATUS = "CHANGE_START_BUTTON_STATUS";
export const MINUS_SECONDS = "MINUS_SECONDS";
export const GET_SECONDS = "GET_SECONDS";
export const GET_MINUTES = "GET_MINUTES";
export const SET_REMAINING_SECONDS = "SET_REMAINING_SECONDS";
